### ISSUE TITLE
Bad Magic Number

### ISSUE THREAD

**Issue by umop3plsdn** [StareInTheAir/mpv-trakt-sync-daemon#5]
I've installed this on several linux distros and never had a problem like this. I am currently running OpenBSD and no matter how I install this I get the following:
(venv)  da5id@tesla  /usr/local/mpv-trakt-sync-daemon   master  ./sync_daemon.py 
Traceback (most recent call last):
  File "./sync_daemon.py", line 14, in <module>
    import trakt_key_holder

do you have any suggestions? i'm just stumped... At first I thought maybe for some strange reason it was trying to use python2 but when i force python2 to run it I get expected errors like: 
Traceback (most recent call last):
  File "./sync_daemon.py", line 7, in <module>
    import urllib.parse
ImportError: No module named parse

**Comment by umop3plsdn** [comment]
actually the only difference I see is that it's a trakt_key_holder is a pyc

**Comment by umop3plsdn** [comment]
Python 3.6.6 btw thank you for even taking the time to look at my issues whenever i get them lol

**Comment by umop3plsdn** [comment]
This worked PERFECTLY thank you!
